### ISSUE TITLE
Finding twitter dataset result.

### ISSUE THREAD

**Issue by divy9881** [LIAAD/KeywordExtractor-Datasets#1]
Can anyone point out a dataset related to twitter posts from this repository? The PDF below gives the source link to this repository for twitter dataset results, which I cannot find in this repo.

http://www.ccc.ipt.pt/~ricardo/ficheiros/Tese_AFarinha.pdf

**Comment by rncampos** [comment]
Problem solved.

**Comment by divy9881** [comment]
Thanks for your help.
